const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('ipcBridge', {
  auth: {
    login: (payload) => ipcRenderer.invoke('auth:login', payload),
    logout: () => ipcRenderer.invoke('auth:logout'),
    checkSession: (payload) => ipcRenderer.invoke('auth:checkSession', payload),
  },
  user: {
    changePassword: (payload) => ipcRenderer.invoke('user:changePassword', payload),
  },
  stock: {
    getAll: () => ipcRenderer.invoke('stock:getAll'),
    getArchived: () => ipcRenderer.invoke('stock:getArchived'),
    getById: (payload) => ipcRenderer.invoke('stock:getById', payload),
    create: (payload) => ipcRenderer.invoke('stock:create', payload),
    update: (payload) => ipcRenderer.invoke('stock:update', payload),
    addInbound: (payload) => ipcRenderer.invoke('stock:addInbound', payload),
    updateTransaction: (payload) => ipcRenderer.invoke('stock:updateTransaction', payload),
    checkDuplicate: (payload) => ipcRenderer.invoke('stock:checkDuplicate', payload),
    archive: (payload) => ipcRenderer.invoke('stock:archive', payload),
    restore: (payload) => ipcRenderer.invoke('stock:restore', payload),
  },
  suppliers: {
    getAll: () => ipcRenderer.invoke('suppliers:getAll'),
    getById: (payload) => ipcRenderer.invoke('suppliers:getById', payload),
    create: (payload) => ipcRenderer.invoke('suppliers:create', payload),
    update: (payload) => ipcRenderer.invoke('suppliers:update', payload),
    delete: (payload) => ipcRenderer.invoke('suppliers:delete', payload),
  },
  employees: {
    getAll: () => ipcRenderer.invoke('employees:getAll'),
    getById: (payload) => ipcRenderer.invoke('employees:getById', payload),
    create: (payload) => ipcRenderer.invoke('employees:create', payload),
    update: (payload) => ipcRenderer.invoke('employees:update', payload),
    setStatus: (payload) => ipcRenderer.invoke('employees:setStatus', payload),
    addOperation: (payload) => ipcRenderer.invoke('employees:addOperation', payload),
    addPayment: (payload) => ipcRenderer.invoke('employees:addPayment', payload),
    updatePayment: (payload) => ipcRenderer.invoke('employees:updatePayment', payload),
    deletePayment: (payload) => ipcRenderer.invoke('employees:deletePayment', payload),
  },
  cutting: {
    getKpis: () => ipcRenderer.invoke('cutting:getKpis'),
    getAll: () => ipcRenderer.invoke('cutting:getAll'),
    getById: (payload) => ipcRenderer.invoke('cutting:getById', payload),
    getFabrics: () => ipcRenderer.invoke('cutting:getFabrics'),
    getFabricColors: (payload) => ipcRenderer.invoke('cutting:getFabricColors', payload),
    getNonFabricItems: () => ipcRenderer.invoke('cutting:getNonFabricItems'),
    getModelSuggestions: () => ipcRenderer.invoke('cutting:getModelSuggestions'),
    getPartSuggestions: (payload) => ipcRenderer.invoke('cutting:getPartSuggestions', payload),
    getPartsInventory: () => ipcRenderer.invoke('cutting:getPartsInventory'),
    getAvailableSizesForModel: (payload) => ipcRenderer.invoke('cutting:getAvailableSizesForModel', payload),
    getAvailableColorsForModelSize: (payload) => ipcRenderer.invoke('cutting:getAvailableColorsForModelSize', payload),
    create: (payload) => ipcRenderer.invoke('cutting:create', payload),
    getFabricBatches: (payload) => ipcRenderer.invoke('cutting:getFabricBatches', payload),
    getMaterialBatches: (payload) => ipcRenderer.invoke('cutting:getMaterialBatches', payload),
  },
  tailors: {
    getAll: () => ipcRenderer.invoke('tailors:getAll'),
    getById: (payload) => ipcRenderer.invoke('tailors:getById', payload),
    create: (payload) => ipcRenderer.invoke('tailors:create', payload),
    update: (payload) => ipcRenderer.invoke('tailors:update', payload),
    setStatus: (payload) => ipcRenderer.invoke('tailors:setStatus', payload),
    addPayment: (payload) => ipcRenderer.invoke('tailors:addPayment', payload),
    updatePayment: (payload) => ipcRenderer.invoke('tailors:updatePayment', payload),
    deletePayment: (payload) => ipcRenderer.invoke('tailors:deletePayment', payload),
  },
  distribution: {
    getKpis: () => ipcRenderer.invoke('distribution:getKpis'),
    getSummary: () => ipcRenderer.invoke('distribution:getSummary'),
    getDetailByTailor: (payload) => ipcRenderer.invoke('distribution:getDetailByTailor', payload),
    getActiveTailors: () => ipcRenderer.invoke('distribution:getActiveTailors'),
    getAvailablePartsForModel: (payload) => ipcRenderer.invoke('distribution:getAvailablePartsForModel', payload),
    getAvailabilityForModel: (payload) => ipcRenderer.invoke('distribution:getAvailabilityForModel', payload),
    getModelSuggestions: () => ipcRenderer.invoke('distribution:getModelSuggestions'),
    getBatchesForTailor: (payload) => ipcRenderer.invoke('distribution:getBatchesForTailor', payload),
    getModelsWithPieces: () => ipcRenderer.invoke('distribution:getModelsWithPieces'),
    getSizesForModel: (payload) => ipcRenderer.invoke('distribution:getSizesForModel', payload),
    getColorsForModelSize: (payload) => ipcRenderer.invoke('distribution:getColorsForModelSize', payload),
    getPartsWithCostForModelSizeColor: (payload) => ipcRenderer.invoke('distribution:getPartsWithCostForModelSizeColor', payload),
    distribute: (payload) => ipcRenderer.invoke('distribution:distribute', payload),
    return: (payload) => ipcRenderer.invoke('distribution:return', payload),
  },
  pieces: {
    getAvailability: (payload) => ipcRenderer.invoke('pieces:getAvailability', payload),
    getLowStockThreshold: () => ipcRenderer.invoke('pieces:getLowStockThreshold'),
    setLowStockThreshold: (payload) => ipcRenderer.invoke('pieces:setLowStockThreshold', payload),
  },
  lookups: {
    getTypes: () => ipcRenderer.invoke('lookups:getTypes'),
    getColors: () => ipcRenderer.invoke('lookups:getColors'),
    getUnits: () => ipcRenderer.invoke('lookups:getUnits'),
    createType: (payload) => ipcRenderer.invoke('lookups:createType', payload),
    createColor: (payload) => ipcRenderer.invoke('lookups:createColor', payload),
    createUnit: (payload) => ipcRenderer.invoke('lookups:createUnit', payload),
    updateType: (payload) => ipcRenderer.invoke('lookups:updateType', payload),
    updateColor: (payload) => ipcRenderer.invoke('lookups:updateColor', payload),
    updateUnit: (payload) => ipcRenderer.invoke('lookups:updateUnit', payload),
    deleteType: (payload) => ipcRenderer.invoke('lookups:deleteType', payload),
    deleteColor: (payload) => ipcRenderer.invoke('lookups:deleteColor', payload),
    deleteUnit: (payload) => ipcRenderer.invoke('lookups:deleteUnit', payload),
    getModels: () => ipcRenderer.invoke('lookups:getModels'),
    createModel: (payload) => ipcRenderer.invoke('lookups:createModel', payload),
    updateModel: (payload) => ipcRenderer.invoke('lookups:updateModel', payload),
    deleteModel: (payload) => ipcRenderer.invoke('lookups:deleteModel', payload),
    getParts: () => ipcRenderer.invoke('lookups:getParts'),
    createPart: (payload) => ipcRenderer.invoke('lookups:createPart', payload),
    updatePart: (payload) => ipcRenderer.invoke('lookups:updatePart', payload),
    deletePart: (payload) => ipcRenderer.invoke('lookups:deletePart', payload),
    getSizes: () => ipcRenderer.invoke('lookups:getSizes'),
    createSize: (payload) => ipcRenderer.invoke('lookups:createSize', payload),
    updateSize: (payload) => ipcRenderer.invoke('lookups:updateSize', payload),
    deleteSize: (payload) => ipcRenderer.invoke('lookups:deleteSize', payload),
  },
  qc: {
    getKpis: () => ipcRenderer.invoke('qc:getKpis'),
    getReturnBatchesForQc: () => ipcRenderer.invoke('qc:getReturnBatchesForQc'),
    getRecords: () => ipcRenderer.invoke('qc:getRecords'),
    create: (payload) => ipcRenderer.invoke('qc:create', payload),
  },
  finition: {
    getQcRecordsForFinition: () => ipcRenderer.invoke('finition:getQcRecordsForFinition'),
    getRecords: () => ipcRenderer.invoke('finition:getRecords'),
    create: (payload) => ipcRenderer.invoke('finition:create', payload),
    createStep: (payload) => ipcRenderer.invoke('finition:createStep', payload),
    addToFinalStock: (payload) => ipcRenderer.invoke('finition:addToFinalStock', payload),
  },
  finalStock: {
    getKpis: () => ipcRenderer.invoke('final-stock:getKpis'),
    getRows: (payload) => ipcRenderer.invoke('final-stock:getRows', payload),
    getHistory: (payload) => ipcRenderer.invoke('final-stock:getHistory', payload),
  },
  dashboard: {
    getSnapshotData: () => ipcRenderer.invoke('dashboard:getSnapshotData'),
    getPeriodKpis: (payload) => ipcRenderer.invoke('dashboard:getPeriodKpis', payload),
    getChartData: (payload) => ipcRenderer.invoke('dashboard:getChartData', payload),
  },
  on: (channel, callback) => {
    ipcRenderer.on(channel, (_event, ...args) => callback(...args))
  },
  off: (channel, callback) => {
    ipcRenderer.off(channel, callback)
  },
})
